export const CARGAR_VEHICULOS_PARQUEADOS = "CARGAR_VEHICULOS_PARQUEADOS";
export const NOTIFICAR_CARGA_DE_VEHICULOS = "NOTIFICAR_CARGA_DE_VEHICULOS";
export const REGISTRAR_ENTRADA = "REGISTRAR_ENTRADA";
export const NOTIFICAR_REGISTRO_DE_ENTRADA = "NOTIFICAR_REGISTRO_DE_ENTRADA";
export const REGISTRAR_SALIDA = "REGISTRAR_SALIDA";
export const NOTIFICAR_REGISTRO_DE_SALIDA = "NOTIFICAR_REGISTRO_DE_SALIDA";
export const SOLICITAR_CONFIRMACION_SALIDA = "SOLICITAR_CONFIRMACION_SALIDA"
export const CANCELAR_SALIDA = "CANCELAR_SALIDA"
